bin.includes = META-INF/,\
               .,\
               LICENSE.TXT,\
               CHANGELOG.md,\
               lib/schemas.jar,\
               lib/crac-1.5.0.jar
jars.compile.order = .
source.. = src/main/java/,\
           src/main/resources/,\
           src/generated/java/
output.. = bin/
src.includes = LICENSE.TXT
bin.excludes = maven.properties
